### ISSUE TITLE
Surface 3 Laptop: Issue enabling ipts option in brunch: Terminated with status 234

### ISSUE THREAD

**Issue by rexsububi** [ipts-linux-org/ipts-linux-new#6]
Hello
I was hoping that someone could share some details about what status 234 means.

My touchscreen is not working and I ran: sudo dmesg | grep ipts

[    0.000000] Command line: BOOT_IMAGE=(hd0,7)/kernel-5.10 boot=local noresume noswap options=ipts,advanced_als loglevel=7 disablevmx=off cros_secure cros_debug
[    0.060650] Kernel command line: BOOT_IMAGE=(hd0,7)/kernel-5.10 boot=local noresume noswap options=ipts,advanced_als loglevel=7 disablevmx=off cros_secure cros_debug
[    1.378488]     options=ipts,advanced_als
[   85.150690] brunch: /rootc/patches/99-bootscripts.sh success
[   85.337723] brunch: /rootc/patches/99-ipts.sh ipts enabled
[   85.349726] brunch: /rootc/patches/99-ipts.sh success
[   91.771623] ipts: loading out-of-tree module taints kernel.
[   91.788611] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting IPTS
[   91.792661] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Device 045E:0984 ready
[   92.807472] init: ipts main process (2382) terminated with status 234

**Comment by mirh** [comment]
https://gitter.im/linux-surface/support?at=5fe10086aa6bb528c3637b78 ?
But this is a dead repot.. You'd better follow up with the https://github.com/linux-surface/linux-surface guys

**Comment by rexsububi** [comment]
Like so many issues I find on git, it is solved on the main page! Wahoo, thanks for the help.
